title: Mishan Phiri
logo: /images/20220623_152819.jpg
Description: "Bachelor of Business Science specializing in Analytics student at the University of Cape Town. I am currently in my final year. 
I have a passion for data and technology with an interest in Machine Learning. I am 
currently doing my final year project in approximating the Gaussian Problem. I often work in teams with leadership 
responsibility and run my own small business. I love learning and I am currently working on refining my skills to become a Data Scientist" 
#show_downloads: true
theme: jekyll-theme-minimal
#plugins: jekyll-include-cache
